{% set name = "gettsim" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gettsim-{{ version }}.tar.gz
  sha256: 8476b2ab7b7a2878ebe01e66011b5fa02a4ec7e7b1a08671c0bae2cfb0606ad2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.0
    - pip
  run:
    - python >=3.9
    - astor
    - dags
    - networkx
    - numpy
    - numpy_groupies
    - pandas
    - plotly
    - pygments
    - pygraphviz
    - pytest
    - pyyaml

test:
  imports:
    - gettsim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iza-institute-of-labor-economics/gettsim
  summary: The German Taxes and Transfers SIMulator
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmgaudecker
