{% set name = "gettsim" %}
{% set version = "1.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/gettsim-{{ version }}.tar.gz
  sha256: a6f14288f30e591afa874d99256fea0b3c60726a1d42a84907168103aded4180

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - ttsim-backend >=1.2

test:
  imports:
    - gettsim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: The German Taxes and Transfers SIMulator
  license: AGPL-3.0-only
  license_file: LICENSE
  home: https://github.com/ttsim-dev/gettsim

extra:
  recipe-maintainers:
    - hmgaudecker
    - MImmesberger
